### ISSUE TITLE
yappari (2.0.3)  Bug report

### ISSUE THREAD

**Issue by newone2** [agamez/yappari#22]
Hi, i hope that's the right place, if not sorry.
I'm surely you still noticed those little "bugs" but....

*notification when typing doesn't work in both ways (single Chat)
 => shows nothing

*infrastructure to report which participant is composing message on
 group chats -  Doesn't work => shows nothing

**Comment by CODeRUS** [comment]
Please prefer to create different issues for each problem next time.

**Comment by newone2** [comment]
Excuse me, 
I will make sure next time.
