### ISSUE TITLE
Contact names

### ISSUE THREAD

**Issue by kori4r2** [agamez/yappari#27]
Hi, when the protocol issue happened I was in a hurry to use yappari again and replaced the bin file before the update actually happened. I can use yappari just fine but can't see any contact nickname and cannot create chat with any of my contacts, they only show up on the list after they send me a message, or if they are in a group chat i belong to, wich is strange because when the conversation pops up it has all old messages there, but the new ones show a phone number instead of nickname

**Comment by agamez** [comment]
Is this still happening after latest 2.0.7 release? It included database changes and it may have been solved for you.

If that's not the case, the easiest way to solve it is to close Yappari, remove your rosterdb file (/home/user/.yappari/roster.db) and start Yappari again.

Sorry for the long time dealing with your issue :/

**Comment by kori4r2** [comment]
Deleting the file will not cause any problems, right?

**Comment by agamez** [comment]
You will lose custom aliases and the such, but given that you can't even see those, I see no good reason not to delete the file.

You can, of course, keep a backup of it and roll back if the need arises. No one else I know of is experiencing those problems, so the odds are definitely that you have a corrupted roster file.

**Comment by kori4r2** [comment]
I tried deleting the file and nothing changed. A couple updates after I posted this issue, some of the names started to show up, but only the names of people I have saved in my contact list (that's how it is right now). Before the issue happened, it would always show the person's name even if said person was not in my contact list

**Comment by agamez** [comment]
All right, what you're experiencing now is a known issue. It'll be fixed on next release scheduled for this weekend.

**Comment by kori4r2** [comment]
thanks a lot. As soon as I update and test I'll close this

**Comment by kori4r2** [comment]
fixed, thanks again
