### ISSUE TITLE
Yappari 2.0.10 - not connecting

### ISSUE THREAD

**Issue by nelsonslobo** [agamez/yappari#35]
Hi,
I have the latest Yappari 2.0.10 but its not connecting to the sever.
I get the message 'Sever connection closed'
I also don't know how to get the logs. 

Please help.

Regards
Nelson

**Comment by agamez** [comment]
You can find Yappari's log messages at
/home/user/.config/scorpius/yappari.log

You can send just the last couple dozen of lines of the file, and edit it
to remove personal information you may find.

2015-04-10 6:20 GMT+02:00 nelsonslobo notifications@github.com:

> Hi,
> I have the latest Yappari 2.0.10 but its not connecting to the sever.
> I get the message 'Sever connection closed'
> I also don't know how to get the logs.
> 
> Please help.
> 
> Regards
> Nelson
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agamez/yappari/issues/35.

## 

Álvaro Gámez Machado

**Comment by nelsonslobo** [comment]
Thanks got it. heres are the last few lines. 

Connecting to c.whatsapp.net:443...
Connected successfully
OUTGOING:
stream:features
<groups_v2>
<presence>
<privacy>
<readreceipts>

OUTGOING:
<auth>
   mechanism=WAUTH-2
   passive=false
   user=61401393862

INCOMING:
stream:start
   from=s.whatsapp.net

INCOMING:
stream:features

INCOMING:
<challenge>
   Content of type challenge length: 20

OUTGOING:
<response>
   Content of type response length: 45

INCOMING:
<failure>
<not-authorized>

There was an IO error: Connection closed by server.
Connection closed.
Stopping timers.
Freeing up the connection.
Freeing up the socket.
Yappari will retry the connection in 10 seconds.
Connecting to c.whatsapp.net:443...
Connected successfully
OUTGOING:
stream:features
<groups_v2>
<presence>
<privacy>
<readreceipts>

OUTGOING:
<auth>
   mechanism=WAUTH-2
   passive=false
   user=61401393862

INCOMING:
stream:start
   from=s.whatsapp.net

INCOMING:
stream:features

INCOMING:
<challenge>
   Content of type challenge length: 20

OUTGOING:
<response>
   Content of type response length: 45

INCOMING:
<failure>
<not-authorized>

There was an IO error: Connection closed by server.
Connection closed.
Stopping timers.
Freeing up the connection.
Freeing up the socket.
Yappari will retry the connection in 10 seconds.
Connecting to c.whatsapp.net:443...
Connected successfully
OUTGOING:
stream:features
<groups_v2>
<presence>
<privacy>
<readreceipts>

OUTGOING:
<auth>
   mechanism=WAUTH-2
   passive=false
   user=61401393862

INCOMING:
stream:start
   from=s.whatsapp.net

INCOMING:
stream:features

INCOMING:
<challenge>
   Content of type challenge length: 20

OUTGOING:
<response>
   Content of type response length: 45

INCOMING:
<failure>
<not-authorized>

There was an IO error: Connection closed by server.
Connection closed.
Stopping timers.
Freeing up the connection.
Freeing up the socket.
Yappari will retry the connection in 10 seconds.
Connecting to c.whatsapp.net:443...
Connected successfully
OUTGOING:
stream:features
<groups_v2>
<presence>
<privacy>
<readreceipts>

OUTGOING:
<auth>
   mechanism=WAUTH-2
   passive=false
   user=61401393862

INCOMING:
stream:start
   from=s.whatsapp.net

INCOMING:
stream:features

INCOMING:
<challenge>
   Content of type challenge length: 20

OUTGOING:
<response>
   Content of type response length: 45

INCOMING:
<failure>
<not-authorized>

There was an IO error: Connection closed by server.
Connection closed.
Stopping timers.
Freeing up the connection.
Freeing up the socket.
Yappari will retry the connection in 10 seconds.
User has quit the application
Application destroyed

**Comment by nelsonslobo** [comment]
Hi any update on my defect.

Nelson

**Comment by agamez** [comment]
I can't see any reason for that :/ It's a remote chance, but please try
reinstalling Yappari with latest version.

2015-04-11 17:24 GMT+02:00 nelsonslobo notifications@github.com:

> Hi any update on my defect.
> 
> Nelson
> 
> On Fri Apr 10 20:38:14 2015 Alvaro G. M. notifications@github.com wrote:
> 
> > You can find Yappari's log messages at
> > /home/user/.config/scorpius/yappari.log
> > 
> > You can send just the last couple dozen of lines of the file, and edit it
> > to remove personal information you may find.
> > 
> > 2015-04-10 6:20 GMT+02:00 nelsonslobo notifications@github.com:
> > 
> > > Hi,
> > > I have the latest Yappari 2.0.10 but its not connecting to the sever.
> > > I get the message 'Sever connection closed'
> > > I also don't know how to get the logs.
> > > 
> > > Please help.
> > > 
> > > Regards
> > > Nelson
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/agamez/yappari/issues/35.
> > 
> > ## 
> > 
> > Álvaro Gámez Machado
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/agamez/yappari/issues/35#issuecomment-91510559
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agamez/yappari/issues/35#issuecomment-91869243.

## 

Álvaro Gámez Machado

**Comment by nelsonslobo** [comment]
Hi,
i have the latest version-2.0.10 and reinstalled the app. How to completely uninstall yappari from my N900?

Thanks
Nelson.

**Comment by agamez** [comment]
You can execute as root dpkg -P yappari. It won't delete your personal
data. If you desire to do so, you'd have to remove also /home/user/.yappari
and /home/user/.config/scorpius

Removing the last directory will force registration again.

2015-04-12 23:15 GMT+02:00 nelsonslobo notifications@github.com:

> Hi,
> i have the latest version-2.0.10 and reinstalled the app. How to
> completely uninstall yappari from my N900?
> 
> Thanks
> Nelson.
> 
> On Mon Apr 13 03:52:07 2015 Alvaro G. M. notifications@github.com wrote:
> 
> > I can't see any reason for that :/ It's a remote chance, but please try
> > reinstalling Yappari with latest version.
> > 
> > 2015-04-11 17:24 GMT+02:00 nelsonslobo notifications@github.com:
> > 
> > > Hi any update on my defect.
> > > 
> > > Nelson
> > > 
> > > On Fri Apr 10 20:38:14 2015 Alvaro G. M. notifications@github.com
> > > wrote:
> > > 
> > > > You can find Yappari's log messages at
> > > > /home/user/.config/scorpius/yappari.log
> > > > 
> > > > You can send just the last couple dozen of lines of the file, and
> > > > edit it to remove personal information you may find.
> > > > 
> > > > 2015-04-10 6:20 GMT+02:00 nelsonslobo notifications@github.com:
> > > > 
> > > > > Hi,
> > > > > I have the latest Yappari 2.0.10 but its not connecting to the
> > > > > sever. I get the message 'Sever connection closed'
> > > > > I also don't know how to get the logs.
> > > > > 
> > > > > Please help.
> > > > > 
> > > > > Regards
> > > > > Nelson
> > > > > 
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > https://github.com/agamez/yappari/issues/35.
> > > > 
> > > > ## 
> > > > 
> > > > Álvaro Gámez Machado
> > > > 
> > > > ---
> > > > 
> > > > Reply to this email directly or view it on GitHub:
> > > > https://github.com/agamez/yappari/issues/35#issuecomment-91510559
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/agamez/yappari/issues/35#issuecomment-91869243.
> > 
> > ## 
> > 
> > Álvaro Gámez Machado
> > 
> > ---
> > 
> > Reply to this email directly or view it on GitHub:
> > https://github.com/agamez/yappari/issues/35#issuecomment-92095674
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agamez/yappari/issues/35#issuecomment-92134586.

## 

Álvaro Gámez Machado

**Comment by nelsonslobo** [comment]
Removed Yappari. Removed all the files and reinstalled.
But now its not registering. I didnt get any SMS. Also if I choose Call Me
option - it say Registration couldnt be completed. Server Response was:
Blocked.

Does that mean I am blocked by Whatsapp. What should I do?

Rgds
Nelson

**Comment by agamez** [comment]
Yep. That's the reason it was refusing your connections before, sorry.

Read http://talk.maemo.org/showpost.php?p=1465316&postcount=663 and previous/next posts from coderus that explain exactly what to do.

**Comment by nelsonslobo** [comment]
thanks Dude for all your help.
Really Gratefull

Rgds
Nelson
