### ISSUE TITLE
Auto-download options missing from menu/UI

### ISSUE THREAD

**Issue by sicelo** [agamez/yappari#37]
In the past, there was a setting in Yappari to control whether received files are downloaded automaticslly or not, based on a threshold you could set through the UI.
This UI option is missing now. However, the corresponding setting in yappari.conf stil seems to work.
Could it be restored to the UI?

**Comment by agamez** [comment]
I hadn't noticed this. It's now solved on develop branch, although I won't be releasing a new version until a couple more things are fixed.

Thanks for the report!
