### ISSUE TITLE
Consistent Crash After Syncing Contacts

### ISSUE THREAD

**Issue by sicelo** [agamez/yappari#41]
On my N900, Yappari crashes every time immediately at the end of contacts sync process. I do not know what information you may need to track down the issue, but can send anything you request.

The consequence of this issue is that I get temporary bans from Whatsapp (http://www.whatsapp.com/faq/en/general/28030003)

Any assistance will be appreciated.

**Comment by agamez** [comment]
That's quite strange, I've never experienced anything similar.

My first guess is some of your contacts may have data that WA considers
invalid. Do you remember if any of your contacts may have strange data,
such as rare characters, non alphanumeric phone number or something like
that?

2015-07-09 9:31 GMT+02:00 sicelo notifications@github.com:

> On my N900, Yappari crashes every time immediately at the end of contacts
> sync process. I do not know what information you may need to track down the
> issue, but can send anything you request.
> 
> The consequence of this issue is that I get temporary bans from Whatsapp (
> http://www.whatsapp.com/faq/en/general/28030003)
> 
> Any assistance will be appreciated.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agamez/yappari/issues/41.

## 

Álvaro Gámez Machado

**Comment by sicelo** [comment]
There isn't one with such characters. I do have an Andre with accent on the E but I can remove him from my contacts to see.

Would perhaps contacts having emojis in their status messages result in this?

**Comment by agamez** [comment]
I don't think the accents can be a problem (I'm spanish so I have lots of
people with accents, mine being the first).

And I have at least one person with emojis on the status, so it probably
isn't that either.

How many people do you have on your contacts list? Maybe we're reaching
some limit...

2015-07-09 10:15 GMT+02:00 sicelo notifications@github.com:

> There isn't one with such characters. I do have an Andre with accent on
> the E but I can remove him from my contacts to see.
> 
> Would perhaps contacts having emojis in their status messages result in
> this?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/agamez/yappari/issues/41#issuecomment-119869813.

## 

Álvaro Gámez Machado

**Comment by sicelo** [comment]
I have 253 contacts on my phone. A few only have email addresses or other online accounts, not phone numbers. Dumping roster.db indicates that 150 of them are on Whatsapp

**Comment by sicelo** [comment]
After a long absence from Whatsapp (blocked), I am now back on Yappari using a new number. This crash is still happening on syncing contacts. Every time. Perhaps I should try strace and send you.

**Comment by agamez** [comment]
That could help indeed. I think I'll be releasing too a debug version that allows crashes to generate useful coredumps.

**Comment by sicelo** [comment]
No crash when run with strace, and did not crash when run without strace afterwards. Will monitor and update you.
