### ISSUE TITLE
Can't read answers from contacts

### ISSUE THREAD

**Issue by audiophilo** [agamez/yappari#43]
**FIRST**, thank you for this big effort.

I'm running **Yappari 2.0.21 build 5222** on a **Nokia n900** and everything works fine except that i can't read the answers of some of my contacts. 
I'll try to make myself clearer: i can send and receive messages to and from many of my contacts but for some of them i can only send. They can read what i have written but when they answer nothing appears in my chat.

Does it make any sense to you?
Thank you in advance.

**Comment by agamez** [comment]
Should be fixed on 2.0.22. See http://talk.maemo.org/showpost.php?p=1486191&postcount=1217 for more info
